#!/usr/bin/expect
eval spawn openssl req -new -key server.key -out server.csr
set prompt "Enter pass phrase for server.key:"
interact -o -nobuffer -re $prompt return
send "sslisasecreteweapon\r"
interact