"""
# == Modelling ReThinkDB tables in my collection ==
"""

# My ORM library of choise with RethinkDB
from rethinkORM import RethinkModel

TESTING_TABLE = 'test'

# == Implements ORM models to use inside my Database ==

class GenericORMModel(RethinkModel):
    """ The most generic model """
    # Setup table to use inside RethinkDB
    table = TESTING_TABLE
    # 'id' (autogenerated) is the primary key in a RethinkModel

    @classmethod
    def list_attributes(cls):
        """ Cycle class attributes to get a list.
        Usable on the class, rather then instance"""
        attributes = {}

        for key in cls.__dict__.keys():
            # skip:
            # 1. magic methods ( e.g. __name__ )
            # 2. and also "table" name
            if key[0:2] != "__" and key != "table":
                value = getattr(cls, key)
                # skip methods (which are not strings and integer?)
                if isinstance(value, str) or isinstance(value, int):
                    #print "Attr:", key, value
                    attributes[key] = value
        return attributes

class DataDump(GenericORMModel):
    """ A simple container for data dumping """
    table = 'dump'
    # Attributes:
    key = 'label'
    value = 'associatedtolabel'

class APIUser(GenericORMModel):
    """ Security model """
    table = 'users'
    username = "unknown"

    """ Other attributes:
    password = db.StringProperty(required=True)
    salt = db.StringProperty()
    role = db.StringProperty()
    created = db.DateTimeProperty(auto_now_add=True)
    modified = db.DateTimeProperty(auto_now=True)
    """


