# Everything here should be HTTPS!
# use certificates!!

##############################
## Production database
dbdata:
  extends:
    file: common.yml
    service: dbdata
rdb:
    extends:
        file: common.yml
        service: rdb
    volumes_from:
         - dbdata     # Import data directory from storage container
# # We can join as many as we want
# rdbslave:
#     image: rethinkdb
#     command: rethinkdb --join master:29015 --bind all
#     links:
#         - rdb:master
# # To clean:
# #$ docker exec -it frapi_api_1 python clean_cluster_issues.py

##############################
## REST API
pycode:
    extends:
        file: common.yml
        service: pycode
api:
    extends:
        file: common.yml
        service: api
    # if i use environment variables it does not work...
    command: gunicorn -c gunicorn.conf.py --bind '0.0.0.0:5000' main:app
    exposes:
        - "5000"
    volumes_from:
        - pycode
    links:
        - rdb:db
updata:
    extends:
        file: common.yml
        service: updata
fileapi:
    extends:
        file: common.yml
        service: fileapi
    command: gunicorn -c gunicorn.conf.py --bind '0.0.0.0:6000' file:app
    exposes:
        - "6000"
    volumes_from:
        - pycode
        - updata

##############################
## Periodic tasks
backupdata:
    extends:
        file: common.yml
        service: backupdata
tasker:
    build: ../docker/tasks
    links:
        - rdb:db #Slave?
    volumes_from:
        - backupdata

##########################
## PROXY and HTTPS
sslproxy:
    extends:
        file: common.yml
        service: proxy
    volumes:
        - ../certificates/privateUnKey.pem:/etc/nginx/server.key
        - ../certificates/publicCert.pem:/etc/nginx/server.crt
        - ../docker/proxy/ssl-enabled.conf:/etc/nginx/sites-enabled/production
    ports:
        - "80:80"
        - "443:443"
    links:
        - api:api
        - fileapi:fapi
    volumes_from:
        - updata
##########################
